### PR TITLE
bugfix: Modify upload and submit  buttons are only available to be clicked when needed.

### PR DESCRIPTION
**Pull request by hojihun5516**
We found a problem.
The problem occurred when the submit button was clicked without a file.
and I could click the submit button when using the speech to text function.
It made a problem

I fixed it like this.
1. If the file is not on the state then we will can't click submit button
2. We can't click upload and submit button while working speech to text function

### CODE REVIEW

**Comment by rayleighko** [comment]
what is 'a bug'? could you explain to me?

**Comment by rayleighko** [comment]
is this https://github.com/teamthesol/boggler/issues/63?

**Comment by hojihun5516** [comment]
Yes. These are the issue numbers for bug resolution.
#63 
#54

**Comment by rayleighko** [comment]
Ok.

**Pull request merged**
